In [4]:
from pandasql import sqldf
import os
import pandas as pd

In [6]:
url = "https://raw.githubusercontent.com/syntagmatic/gapminder-csv/refs/heads/master/gapminder.csv"
df = pd.read_csv(url)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79309 entries, 0 to 79308
Columns: 537 entries, geo to yearly_co2_emissions_1000_tonnes
dtypes: float64(535), int64(1), object(1)
memory usage: 324.9+ MB

In [8]:
sqldf("SELECT * FROM df LIMIT 5") #children_per_woman_total_fertility life_expetancy_years

   geo  time  ... working_hours_per_week yearly_co2_emissions_1000_tonnes
0  afg  1700  ...                   None                             None
1  afg  1800  ...                   None                             None
2  afg  1801  ...                   None                             None
3  afg  1802  ...                   None                             None
4  afg  1803  ...                   None                             None

[5 rows x 537 columns]

In [11]:
#sqldf("SELECT children_per_woman_total_fertility, life_expectancy_years FROM df LIMIT 10")
sqldf("SELECT geo, time, children_per_woman_total_fertility, life_expectancy_years FROM df LIMIT 10")

   geo  time  children_per_woman_total_fertility  life_expectancy_years
0  afg  1700                                 NaN                    NaN
1  afg  1800                                 7.0                  28.21
2  afg  1801                                 7.0                  28.20
3  afg  1802                                 7.0                  28.19
4  afg  1803                                 7.0                  28.18
5  afg  1804                                 7.0                  28.17
6  afg  1805                                 7.0                  28.16
7  afg  1806                                 7.0                  28.15
8  afg  1807                                 7.0                  28.14
9  afg  1808                                 7.0                  28.13

In [12]:
sqldf("SELECT geo, time, children_per_woman_total_fertility, life_expectancy_years FROM df WHERE geo='arg' and time>1975 LIMIT 10")

   geo  time  children_per_woman_total_fertility  life_expectancy_years
0  arg  1976                                3.37                  67.76
1  arg  1977                                3.39                  68.20
2  arg  1978                                3.39                  68.84
3  arg  1979                                3.37                  69.38
4  arg  1980                                3.33                  69.85
5  arg  1981                                3.27                  70.16
6  arg  1982                                3.21                  70.55
7  arg  1983                                3.16                  70.62
8  arg  1984                                3.12                  70.93
9  arg  1985                                3.09                  71.33

In [17]:
sqldf("SELECT geo, time, children_per_woman_total_fertility, life_expectancy_years FROM df WHERE geo IN ('col','arg') and time>2000")

     geo  time  children_per_woman_total_fertility  life_expectancy_years
0    arg  2001                                2.54                  74.38
1    arg  2002                                2.52                  74.48
2    arg  2003                                2.50                  74.63
3    arg  2004                                2.47                  74.90
4    arg  2005                                2.45                  75.15
..   ...   ...                                 ...                    ...
195  col  2096                                 NaN                    NaN
196  col  2097                                 NaN                    NaN
197  col  2098                                 NaN                    NaN
198  col  2099                                 NaN                    NaN
199  col  2100                                 NaN                    NaN

[200 rows x 4 columns]

In [19]:
sqldf("SELECT geo, time, children_per_woman_total_fertility, life_expectancy_years FROM df WHERE geo IN ('col','arg') AND time = 2000")

   geo  time  children_per_woman_total_fertility  life_expectancy_years
0  arg  2000                                2.56                  74.21
1  col  2000                                2.39                  73.25

In [20]:
sqldf("SELECT geo, time, children_per_woman_total_fertility, life_expectancy_years FROM df WHERE geo IN ('col','arg','mex') AND time = 2000")

   geo  time  children_per_woman_total_fertility  life_expectancy_years
0  arg  2000                                2.56                  74.21
1  col  2000                                2.39                  73.25
2  mex  2000                                2.72                  74.61

In [21]:
sqldf("SELECT DISTINCT geo FROM df")

             geo
0            afg
1            ago
2            arg
3            arm
4            aus
..           ...
259    yem_south
260          yug
261  korea_union
262          maf
263        world

[264 rows x 1 columns]

In [24]:
sqldf("SELECT geo, gdp_total_yearly_growth FROM df WHERE geo='per' AND time BETWEEN 1985 AND 2000 ")

    geo  gdp_total_yearly_growth
0   per                  2.03300
1   per                 10.08000
2   per                  8.61900
3   per                 -8.18500
4   per                -12.21000
5   per                 -5.13500
6   per                  2.39300
7   per                 -1.05400
8   per                  5.49200
9   per                 13.35000
10  per                  8.37600
11  per                  2.14600
12  per                  8.49600
13  per                  0.04935
14  per                  0.87260
15  per                  3.04900

In [26]:
sqldf("SELECT geo, time, gdp_total_yearly_growth FROM df WHERE geo='per' AND time BETWEEN 1985 AND 2000 ORDER BY time DESC")

    geo  time  gdp_total_yearly_growth
0   per  2000                  3.04900
1   per  1999                  0.87260
2   per  1998                  0.04935
3   per  1997                  8.49600
4   per  1996                  2.14600
5   per  1995                  8.37600
6   per  1994                 13.35000
7   per  1993                  5.49200
8   per  1992                 -1.05400
9   per  1991                  2.39300
10  per  1990                 -5.13500
11  per  1989                -12.21000
12  per  1988                 -8.18500
13  per  1987                  8.61900
14  per  1986                 10.08000
15  per  1985                  2.03300

In [27]:
sqldf("SELECT geo, time, gdp_total_yearly_growth FROM df WHERE geo='arg' AND time BETWEEN 1990 AND 2010 ORDER BY time DESC")

    geo  time  gdp_total_yearly_growth
0   arg  2010                   8.8850
1   arg  2009                   0.5982
2   arg  2008                   6.4950
3   arg  2007                   8.3880
4   arg  2006                   8.2050
5   arg  2005                   9.0800
6   arg  2004                   8.8820
7   arg  2003                   8.7560
8   arg  2002                 -11.1200
9   arg  2001                  -4.5230
10  arg  2000                  -0.8075
11  arg  1999                  -3.3760
12  arg  1998                   3.9930
13  arg  1997                   8.3440
14  arg  1996                   5.7560
15  arg  1995                  -2.6960
16  arg  1994                   6.1230
17  arg  1993                   6.0380
18  arg  1992                  10.0100
19  arg  1991                  10.8000
20  arg  1990                  -1.8520

In [32]:
sqldf("SELECT time, MAX(gdp_total_yearly_growth) AS max_gdp FROM df WHERE geo='mex'")

   time  MAX(gdp_total_yearly_growth)
0  1950                         12.22

In [33]:
sqldf("SELECT MAX(gdp_total_yearly_growth), geo FROM df GROUP BY geo LIMIT 20")

    MAX(gdp_total_yearly_growth)        geo
0                            NaN       abkh
1                          18.76        abw
2                          28.28        afg
3                          23.19        ago
4                          24.56        aia
5                            NaN  akr_a_dhe
6                            NaN        ala
7                          11.80        alb
8                          12.99        and
9                          36.37        ant
10                        189.70        are
11                         26.76        arg
12                         17.74        arm
13                         19.46        asm
14                         12.65        atg
15                         33.70        aus
16                         27.33        aut
17                         34.60        aze
18                         26.27        bdi
19                         57.92        bel

In [38]:
sqldf("SELECT MAX(gdp_total_yearly_growth), geo, time FROM df WHERE geo IN ('mex', 'arg', 'per') AND time>1985 AND 2025 GROUP BY geo")

   MAX(gdp_total_yearly_growth)  geo  time
0                        10.800  arg  1991
1                         7.087  mex  1997
2                        13.350  per  1994

In [39]:
sqldf("SELECT MIN(gdp_total_yearly_growth), geo, time FROM df WHERE geo IN ('mex', 'arg', 'per') AND time>1985 AND 2025 GROUP BY geo")

   MIN(gdp_total_yearly_growth)  geo  time
0                        -11.12  arg  2002
1                         -6.40  mex  1995
2                        -12.21  per  1989

In [47]:
my_df = sqldf("SELECT geo, time, gdp_total_yearly_growth, children_per_woman_total_fertility, life_expectancy_years FROM df WHERE geo IN('usa','bra','jpn') AND time>1975 AND life_expectancy_years IS NOT NULL AND gdp_total_yearly_growth IS NOT NULL ORDER BY geo")

In [48]:
my_df

     geo  time  ...  children_per_woman_total_fertility  life_expectancy_years
0    bra  1976  ...                                4.42                  64.12
1    bra  1977  ...                                4.34                  64.64
2    bra  1978  ...                                4.26                  65.11
3    bra  1979  ...                                4.17                  65.54
4    bra  1980  ...                                4.07                  65.86
..   ...   ...  ...                                 ...                    ...
109  usa  2009  ...                                2.00                  78.56
110  usa  2010  ...                                1.93                  78.74
111  usa  2011  ...                                1.90                  78.83
112  usa  2012  ...                                1.90                  78.91
113  usa  2013  ...                                1.96                  78.93

[114 rows x 5 columns]